import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body>
        <nav className="flex p-6 justify-end bg-[#808000] border-[#808000]">
          <Link className="mx-6 text-xl text-white" href="/">Home</Link>
          <Link className="mx-6 text-xl text-white" href="/aboutus">About Us</Link>
          <Link className="mx-6 text-xl text-white" href="/contactus">Contact Us</Link>
          <Link className="mx-6 text-xl text-white" href="/users">Users</Link>
        </nav>
        <hr />
        <div className="h-[100vh] border border-[#808000] flex justify-center items-center">
        {children}
        </div>
      </body>
    </html>
  );
}
